#bundle exec jekyll serve

title: Nogura restaurant
email: nogura.restaurant@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

information:
  address: 
    en: Rossell칩 street, 154, Barcelona
    ca: Carrer del Rossell칩, 154, Barcelona
    es: Calle del Rossell칩, 154, Barcelona
  phone: 93 808 55 55
  schedule:
    en: From tuesday to saturday, from 13:00 to 16:00 and from 20:00 to 00:00
    ca: De dimarts a dissabte, de 13:00 a 16:00 i de 20:00 a 00:00
    es: De martes a s치bado, de 13:00 a 16:00 y de 20:00 a 00:00

# Social
social:
  facebook: nogurarestaurant
  instagram: nogura_restaurant

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

sass:
  style: compressed